using Aiursoft.WeChatExam.Models.ExtractViewModels;

namespace Aiursoft.WeChatExam.Services;

public interface IExtractService
{
    /// <summary>
    /// Uses AI to extract knowledge points and questions from the provided material.
    /// Returns the raw JSON string generated by the AI.
    /// </summary>
    Task<string> GenerateJsonAsync(string material, string systemPrompt, CancellationToken token = default);

    /// <summary>
    /// Saves the extracted and verified data into the database.
    /// Handles transaction and data deduplication logic.
    /// </summary>
    Task SaveAsync(List<ExtractedKnowledgePoint> data, Guid categoryId, CancellationToken token = default);
}
